<?php
//----------------------------------------------------------------------------------------------------------------------
use SetBased\Exception\FallenException;

//----------------------------------------------------------------------------------------------------------------------
class FallenExceptionTest extends PHPUnit_Framework_TestCase
{
  //--------------------------------------------------------------------------------------------------------------------
  public function testName()
  {
    try
    {
      throw new FallenException('foo', 'bar');
    }
    catch (Exception $e)
    {
      $this->assertContains('foo', $e->getMessage());
      $this->assertContains('bar', $e->getMessage());
      $this->assertInstanceOf('\RuntimeException', $e);
    }
  }

  //--------------------------------------------------------------------------------------------------------------------
}

//----------------------------------------------------------------------------------------------------------------------
